export const airportTreeData = [
  {
    value: "all",
    label: "全部",
    children: [
      {
        value: "Africa",
        label: "非洲",
        children: [
          { value: "DZ", label: "Algeria" },
          { value: "AO", label: "Angola" },
          { value: "BJ", label: "Benin" },
          { value: "BW", label: "Botswana" },
          { value: "BF", label: "Burkina Faso" },
          { value: "BI", label: "Burundi" },
          { value: "CM", label: "Cameroon" },
          { value: "CV", label: "Cape Verde" },
          { value: "CF", label: "Central African Republic" },
          { value: "TD", label: "Chad" },
          { value: "KM", label: "Comoros" },
          { value: "CD", label: "DR Congo" },
          { value: "CG", label: "Republic of Congo" },
          { value: "CI", label: "Ivory Coast" },
          { value: "DJ", label: "Djibouti" },
          { value: "EG", label: "Egypt" },
          { value: "GQ", label: "Equatorial Guinea" },
          { value: "ER", label: "Eritrea" },
          { value: "SZ", label: "Eswatini" },
          { value: "ET", label: "Ethiopia" },
          { value: "GA", label: "Gabon" },
          { value: "GM", label: "Gambia" },
          { value: "GH", label: "Ghana" },
          { value: "GN", label: "Guinea" },
          { value: "GW", label: "Guinea-Bissau" },
          { value: "KE", label: "Kenya" },
          { value: "LS", label: "Lesotho" },
          { value: "LR", label: "Liberia" },
          { value: "LY", label: "Libya" },
          { value: "MG", label: "Madagascar" },
          { value: "MW", label: "Malawi" },
          { value: "ML", label: "Mali" },
          { value: "MR", label: "Mauritania" },
          { value: "MU", label: "Mauritius" },
          { value: "MA", label: "Morocco" },
          { value: "MZ", label: "Mozambique" },
          { value: "NA", label: "Namibia" },
          { value: "NE", label: "Niger" },
          { value: "NG", label: "Nigeria" },
          { value: "RE", label: "Reunion" },
          { value: "RW", label: "Rwanda" },
          { value: "SN", label: "Senegal" },
          { value: "SC", label: "Seychelles" },
          { value: "SL", label: "Sierra Leone" },
          { value: "SO", label: "Somalia" },
          { value: "ZA", label: "South Africa" },
          { value: "SS", label: "South Sudan" },
          { value: "SD", label: "Sudan" },
          { value: "TZ", label: "Tanzania" },
          { value: "TG", label: "Togo" },
          { value: "TN", label: "Tunisia" },
          { value: "UG", label: "Uganda" },
          { value: "ZM", label: "Zambia" },
          { value: "ZW", label: "Zimbabwe" },
        ],
      },
      {
        value: "Asia",
        label: "亚洲",
        children: [
          { value: "AF", label: "Afghanistan" },
          { value: "AM", label: "Armenia" },
          { value: "AZ", label: "Azerbaijan" },
          { value: "BH", label: "Bahrain" },
          { value: "BD", label: "Bangladesh" },
          { value: "BT", label: "Bhutan" },
          { value: "BN", label: "Brunei" },
          { value: "KH", label: "Cambodia" },
          { value: "CN", label: "China" },
          { value: "CY", label: "Cyprus" },
          { value: "GE", label: "Georgia" },
          { value: "HK", label: "Hong Kong" },
          { value: "IN", label: "India" },
          { value: "ID", label: "Indonesia" },
          { value: "IR", label: "Iran" },
          { value: "IQ", label: "Iraq" },
          { value: "IL", label: "Israel" },
          { value: "JP", label: "Japan" },
          { value: "JO", label: "Jordan" },
          { value: "KZ", label: "Kazakhstan" },
          { value: "KW", label: "Kuwait" },
          { value: "KG", label: "Kyrgyzstan" },
          { value: "LA", label: "Laos" },
          { value: "LB", label: "Lebanon" },
          { value: "MO", label: "Macao" },
          { value: "MY", label: "Malaysia" },
          { value: "MV", label: "Maldives" },
          { value: "MN", label: "Mongolia" },
          { value: "MM", label: "Myanmar" },
          { value: "NP", label: "Nepal" },
          { value: "OM", label: "Oman" },
          { value: "PK", label: "Pakistan" },
          { value: "PH", label: "Philippines" },
          { value: "QA", label: "Qatar" },
          { value: "SA", label: "Saudi Arabia" },
          { value: "SG", label: "Singapore" },
          { value: "KR", label: "South Korea" },
          { value: "LK", label: "Sri Lanka" },
          { value: "SY", label: "Syria" },
          { value: "TW", label: "Taiwan" },
          { value: "TJ", label: "Tajikistan" },
          { value: "TH", label: "Thailand" },
          { value: "TL", label: "Timor-Leste" },
          { value: "TR", label: "Turkey" },
          { value: "TM", label: "Turkmenistan" },
          { value: "AE", label: "United Arab Emirates" },
          { value: "UZ", label: "Uzbekistan" },
          { value: "VN", label: "Vietnam" },
          { value: "YE", label: "Yemen" },
        ],
      },
      {
        value: "Europe",
        label: "欧洲",
        children: [
          { value: "AL", label: "Albania" },
          { value: "AT", label: "Austria" },
          { value: "BY", label: "Belarus" },
          { value: "BE", label: "Belgium" },
          { value: "BA", label: "Bosnia and Herzegovina" },
          { value: "BG", label: "Bulgaria" },
          { value: "HR", label: "Croatia" },
          { value: "CZ", label: "Czech Republic" },
          { value: "DK", label: "Denmark" },
          { value: "EE", label: "Estonia" },
          { value: "FI", label: "Finland" },
          { value: "FR", label: "France" },
          { value: "DE", label: "Germany" },
          { value: "GR", label: "Greece" },
          { value: "HU", label: "Hungary" },
          { value: "IS", label: "Iceland" },
          { value: "IE", label: "Ireland" },
          { value: "IT", label: "Italy" },
          { value: "XK", label: "Kosovo" },
          { value: "LV", label: "Latvia" },
          { value: "LT", label: "Lithuania" },
          { value: "LU", label: "Luxembourg" },
          { value: "MT", label: "Malta" },
          { value: "MD", label: "Moldova" },
          { value: "ME", label: "Montenegro" },
          { value: "NL", label: "Netherlands" },
          { value: "MK", label: "North Macedonia" },
          { value: "NO", label: "Norway" },
          { value: "PL", label: "Poland" },
          { value: "PT", label: "Portugal" },
          { value: "RO", label: "Romania" },
          { value: "RU", label: "Russia" },
          { value: "RS", label: "Serbia" },
          { value: "SK", label: "Slovakia" },
          { value: "SI", label: "Slovenia" },
          { value: "ES", label: "Spain" },
          { value: "SE", label: "Sweden" },
          { value: "CH", label: "Switzerland" },
          { value: "UA", label: "Ukraine" },
          { value: "GB", label: "United Kingdom" },
        ],
      },
      {
        value: "NorthAmerica",
        label: "北美洲",
        children: [
          { value: "AG", label: "Antigua and Barbuda" },
          { value: "BS", label: "Bahamas" },
          { value: "BB", label: "Barbados" },
          { value: "BZ", label: "Belize" },
          { value: "CA", label: "Canada" },
          { value: "CR", label: "Costa Rica" },
          { value: "CU", label: "Cuba" },
          { value: "DM", label: "Dominica" },
          { value: "DO", label: "Dominican Republic" },
          { value: "SV", label: "El Salvador" },
          { value: "GT", label: "Guatemala" },
          { value: "HT", label: "Haiti" },
          { value: "HN", label: "Honduras" },
          { value: "JM", label: "Jamaica" },
          { value: "MX", label: "Mexico" },
          { value: "NI", label: "Nicaragua" },
          { value: "PA", label: "Panama" },
          { value: "TT", label: "Trinidad and Tobago" },
          { value: "US", label: "United States" },
        ],
      },
      {
        value: "Oceania",
        label: "大洋洲",
        children: [
          { value: "AU", label: "Australia" },
          { value: "FJ", label: "Fiji" },
          { value: "PF", label: "French Polynesia" },
          { value: "GU", label: "Guam" },
          { value: "KI", label: "Kiribati" },
          { value: "MH", label: "Marshall Islands" },
          { value: "FM", label: "Micronesia" },
          { value: "NR", label: "Nauru" },
          { value: "NC", label: "New Caledonia" },
          { value: "NZ", label: "New Zealand" },
          { value: "PW", label: "Palau" },
          { value: "PG", label: "Papua New Guinea" },
          { value: "WS", label: "Samoa" },
          { value: "SB", label: "Solomon Islands" },
          { value: "TO", label: "Tonga" },
          { value: "TV", label: "Tuvalu" },
          { value: "VU", label: "Vanuatu" },
        ],
      },
      {
        value: "SouthAmerica",
        label: "南美洲",
        children: [
          { value: "AR", label: "Argentina" },
          { value: "BO", label: "Bolivia" },
          { value: "BR", label: "Brazil" },
          { value: "CL", label: "Chile" },
          { value: "CO", label: "Colombia" },
          { value: "EC", label: "Ecuador" },
          { value: "GY", label: "Guyana" },
          { value: "PY", label: "Paraguay" },
          { value: "PE", label: "Peru" },
          { value: "SR", label: "Suriname" },
          { value: "UY", label: "Uruguay" },
          { value: "VE", label: "Venezuela" },
        ],
      },
    ]
  },
]
export const selectedContinentCountryValues = [
  // Africa
  "DZ",
  "AO",
  "BJ",
  "BW",
  "BF",
  "BI",
  "CM",
  "CV",
  "CF",
  "TD",
  "KM",
  "CD",
  "CG",
  "CI",
  "DJ",
  "EG",
  "GQ",
  "ER",
  "SZ",
  "ET",
  "GA",
  "GM",
  "GH",
  "GN",
  "GW",
  "KE",
  "LS",
  "LR",
  "LY",
  "MG",
  "MW",
  "ML",
  "MR",
  "MU",
  "MA",
  "MZ",
  "NA",
  "NE",
  "NG",
  "RE",
  "RW",
  "SN",
  "SC",
  "SL",
  "SO",
  "ZA",
  "SS",
  "SD",
  "TZ",
  "TG",
  "TN",
  "UG",
  "ZM",
  "ZW",

  // Asia
  "AF",
  "AM",
  "AZ",
  "BH",
  "BD",
  "BT",
  "BN",
  "KH",
  "CN",
  "CY",
  "GE",
  "HK",
  "IN",
  "ID",
  "IR",
  "IQ",
  "IL",
  "JP",
  "JO",
  "KZ",
  "KW",
  "KG",
  "LA",
  "LB",
  "MO",
  "MY",
  "MV",
  "MN",
  "MM",
  "NP",
  "OM",
  "PK",
  "PH",
  "QA",
  "SA",
  "SG",
  "KR",
  "LK",
  "SY",
  "TW",
  "TJ",
  "TH",
  "TL",
  "TR",
  "TM",
  "AE",
  "UZ",
  "VN",
  "YE",

  // Europe
  "AL",
  "AT",
  "BY",
  "BE",
  "BA",
  "BG",
  "HR",
  "CZ",
  "DK",
  "EE",
  "FI",
  "FR",
  "DE",
  "GR",
  "HU",
  "IS",
  "IE",
  "IT",
  "XK",
  "LV",
  "LT",
  "LU",
  "MT",
  "MD",
  "ME",
  "NL",
  "MK",
  "NO",
  "PL",
  "PT",
  "RO",
  "RU",
  "RS",
  "SK",
  "SI",
  "ES",
  "SE",
  "CH",
  "UA",
  "GB",

  // North America
  "AG",
  "BS",
  "BB",
  "BZ",
  "CA",
  "CR",
  "CU",
  "DM",
  "DO",
  "SV",
  "GT",
  "HT",
  "HN",
  "JM",
  "MX",
  "NI",
  "PA",
  "TT",
  "US",

  // Oceania
  "AU",
  "FJ",
  "PF",
  "GU",
  "KI",
  "MH",
  "FM",
  "NR",
  "NC",
  "NZ",
  "PW",
  "PG",
  "WS",
  "SB",
  "TO",
  "TV",
  "VU",

  // South America
  "AR",
  "BO",
  "BR",
  "CL",
  "CO",
  "EC",
  "GY",
  "PY",
  "PE",
  "SR",
  "UY",
  "VE"
];
