export const satelliteTreeData = [
  {
    value: 'all',
    label: '全选',
    children: [
      {
        value: 'Africa',
        label: '非洲',
        children: [
          { value: 'Algeria', label: 'Algeria' },
          { value: 'Egypt', label: 'Egypt' },
          { value: 'Ethiopia', label: 'Ethiopia' },
          { value: 'Kenya', label: 'Kenya' },
          { value: 'Morocco', label: 'Morocco' },
          { value: 'Senegal', label: 'Senegal' },
          { value: 'South Africa', label: 'South Africa' },
          { value: 'Tunisia', label: 'Tunisia' }
        ]
      },
      {
        value: 'Asia',
        label: '亚洲',
        children: [
          { value: 'Armenia', label: 'Armenia' },
          { value: 'Azerbaijan', label: 'Azerbaijan' },
          { value: 'Bahrain', label: 'Bahrain' },
          { value: 'Bangladesh', label: 'Bangladesh' },
          { value: 'Cambodia', label: 'Cambodia' },
          { value: 'China', label: 'China' },
          { value: 'Cyprus', label: 'Cyprus' },
          { value: 'Georgia', label: 'Georgia' },
          { value: 'India', label: 'India' },
          { value: 'Indonesia', label: 'Indonesia' },
          { value: 'Iraq', label: 'Iraq' },
          { value: 'Israel', label: 'Israel' },
          { value: 'Japan', label: 'Japan' },
          { value: 'Jordan', label: 'Jordan' },
          { value: 'Kazakhstan', label: 'Kazakhstan' },
          { value: 'Kuwait', label: 'Kuwait' },
          { value: 'Lebanon', label: 'Lebanon' },
          { value: 'Malaysia', label: 'Malaysia' },
          { value: 'Mongolia', label: 'Mongolia' },
          { value: 'Myanmar', label: 'Myanmar' },
          { value: 'Oman', label: 'Oman' },
          { value: 'Pakistan', label: 'Pakistan' },
          { value: 'Philippines', label: 'Philippines' },
          { value: 'Qatar', label: 'Qatar' },
          { value: 'Saudi Arabia', label: 'Saudi Arabia' },
          { value: 'Singapore', label: 'Singapore' },
          { value: 'Sri Lanka', label: 'Sri Lanka' },
          { value: 'Taiwan', label: 'Taiwan' },
          { value: 'Thailand', label: 'Thailand' },
          { value: 'Turkey', label: 'Turkey' },
          { value: 'Turkmenistan', label: 'Turkmenistan' },
          { value: 'United Arab Emirates', label: 'United Arab Emirates' },
          { value: 'Uzbekistan', label: 'Uzbekistan' },
          // 注意：以下国家在 FLIGHT_CONTINENT_COUNTRIES 中未列出，
          // 但出现在 FLIGHT_COUNTRY_ALIASES 中（如 South Korea, Iran 等）
          // 它们**不会出现在树中**，除非你手动添加到 FLIGHT_CONTINENT_COUNTRIES
        ]
      },
      {
        value: 'Europe',
        label: '欧洲',
        children: [
          { value: 'Austria', label: 'Austria' },
          { value: 'Belarus', label: 'Belarus' },
          { value: 'Belgium', label: 'Belgium' },
          { value: 'Bulgaria', label: 'Bulgaria' },
          { value: 'Croatia', label: 'Croatia' },
          { value: 'Czech Republic', label: 'Czech Republic' },
          { value: 'Denmark', label: 'Denmark' },
          { value: 'Estonia', label: 'Estonia' },
          { value: 'Finland', label: 'Finland' },
          { value: 'France', label: 'France' },
          { value: 'Germany', label: 'Germany' },
          { value: 'Greece', label: 'Greece' },
          { value: 'Hungary', label: 'Hungary' },
          { value: 'Iceland', label: 'Iceland' },
          { value: 'Ireland', label: 'Ireland' },
          { value: 'Italy', label: 'Italy' },
          { value: 'Latvia', label: 'Latvia' },
          { value: 'Lithuania', label: 'Lithuania' },
          { value: 'Luxembourg', label: 'Luxembourg' },
          { value: 'Malta', label: 'Malta' },
          { value: 'Norway', label: 'Norway' },
          { value: 'Poland', label: 'Poland' },
          { value: 'Portugal', label: 'Portugal' },
          { value: 'Romania', label: 'Romania' },
          { value: 'Russia', label: 'Russia' },
          { value: 'Serbia', label: 'Serbia' },
          { value: 'Slovakia', label: 'Slovakia' },
          { value: 'Slovenia', label: 'Slovenia' },
          { value: 'Spain', label: 'Spain' },
          { value: 'Sweden', label: 'Sweden' },
          { value: 'Switzerland', label: 'Switzerland' },
          { value: 'Ukraine', label: 'Ukraine' },
          { value: 'United Kingdom', label: 'United Kingdom' }
        ]
      },
      {
        value: 'North America',
        label: '北美洲',
        children: [
          { value: 'Bahamas', label: 'Bahamas' },
          { value: 'Canada', label: 'Canada' },
          { value: 'Costa Rica', label: 'Costa Rica' },
          { value: 'Dominican Republic', label: 'Dominican Republic' },
          { value: 'El Salvador', label: 'El Salvador' },
          { value: 'Guatemala', label: 'Guatemala' },
          { value: 'Honduras', label: 'Honduras' },
          { value: 'Mexico', label: 'Mexico' },
          { value: 'Panama', label: 'Panama' },
          { value: 'United States', label: 'United States' }
        ]
      },
      {
        value: 'Oceania',
        label: '大洋洲',
        children: [
          { value: 'Australia', label: 'Australia' },
          { value: 'New Zealand', label: 'New Zealand' }
        ]
      },
      {
        value: 'South America',
        label: '南美洲',
        children: [
          { value: 'Argentina', label: 'Argentina' },
          { value: 'Bolivia', label: 'Bolivia' },
          { value: 'Brazil', label: 'Brazil' },
          { value: 'Chile', label: 'Chile' },
          { value: 'Colombia', label: 'Colombia' }
        ]
      }
    ]
  },
];

export const selectedContinentCountryValues = [
  // Africa
  'Algeria',
  'Egypt',
  'Ethiopia',
  'Kenya',
  'Morocco',
  'Senegal',
  'South Africa',
  'Tunisia',

// Asia
  'Armenia',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Cambodia',
  'China',
  'Cyprus',
  'Georgia',
  'India',
  'Indonesia',
  'Iraq',
  'Israel',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kuwait',
  'Lebanon',
  'Malaysia',
  'Mongolia',
  'Myanmar',
  'Oman',
  'Pakistan',
  'Philippines',
  'Qatar',
  'Saudi Arabia',
  'Singapore',
  'Sri Lanka',
  'Taiwan',
  'Thailand',
  'Turkey',
  'Turkmenistan',
  'United Arab Emirates',
  'Uzbekistan',

// Europe
  'Austria',
  'Belarus',
  'Belgium',
  'Bulgaria',
  'Croatia',
  'Czech Republic',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Hungary',
  'Iceland',
  'Ireland',
  'Italy',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'Serbia',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Sweden',
  'Switzerland',
  'Ukraine',
  'United Kingdom',

// North America
  'Bahamas',
  'Canada',
  'Costa Rica',
  'Dominican Republic',
  'El Salvador',
  'Guatemala',
  'Honduras',
  'Mexico',
  'Panama',
  'United States',

// Oceania
  'Australia',
  'New Zealand',

// South America
  'Argentina',
  'Bolivia',
  'Brazil',
  'Chile',
  'Colombia'
];

export const selectedSatelliteContinentCountryValues = [
  // Africa
  'Algeria',
  'Egypt',
  'Ethiopia',
  'Kenya',
  'Morocco',
  'Senegal',
  'South Africa',
  'Tunisia',

// Asia
  'Armenia',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Cambodia',
  'China',
  'Cyprus',
  'Georgia',
  'India',
  'Indonesia',
  'Iraq',
  'Israel',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kuwait',
  'Lebanon',
  'Malaysia',
  'Mongolia',
  'Myanmar',
  'Oman',
  'Pakistan',
  'Philippines',
  'Qatar',
  'Saudi Arabia',
  'Singapore',
  'Sri Lanka',
  'Taiwan',
  'Thailand',
  'Turkey',
  'Turkmenistan',
  'United Arab Emirates',
  'Uzbekistan',

// Europe
  'Austria',
  'Belarus',
  'Belgium',
  'Bulgaria',
  'Croatia',
  'Czech Republic',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Hungary',
  'Iceland',
  'Ireland',
  'Italy',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'Serbia',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Sweden',
  'Switzerland',
  'Ukraine',
  'United Kingdom',

// North America
  'Bahamas',
  'Canada',
  'Costa Rica',
  'Dominican Republic',
  'El Salvador',
  'Guatemala',
  'Honduras',
  'Mexico',
  'Panama',
  'United States',

// Oceania
  'Australia',
  'New Zealand',

// South America
  'Argentina',
  'Bolivia',
  'Brazil',
  'Chile',
  'Colombia'
];
